function acknowledgement
% F=mfilename('fullpath');
% p=fileparts(F);
% 
% [im, map] = imread([p filesep 'postcard.gif']);

txt = {'Please acknowlegde SpliLab by citing our articel:',...
' ',....
'Wüstefeld, A.; Bokelmann, G.H.R.; Zaroli, C.; Barruol, G.',...
'Splitlab - A Shear wave splitting environment in MatLab',...
'Computers and Geosciences, 2006; ???, ????',...
'DOI:??.????/???????????'};
h=msgbox(txt,'Acknowlegdement','help','modal');
waitfor(h)
