function savelist
global config eq
[fname, pname] = uiputfile(...
    {'*.txt','Text file (*.txt)'},....
    'Save current list',...
    fullfile(config.savedir,[config.project(1:end-4) '.txt']));
if isequal(fname,0) || isequal(pname,0)
    return
end

hms   = ' %02.0f:%02.0f:%02.0f';
fid = fopen(fullfile(pname,fname),'w+');
fprintf(fid,'Date\tTime\tJulian day\tFilename\tEv_lat\tEv_lon\tEv_dep\tBazi\tDis\tMw\n');
for i = 1:length(eq)
    if isempty(eq(i).seisfiles{1})
        seisfile = 'No seisfiles';
    else
        seisfile = dname(eq(i).date(1),eq(i).date(2),eq(i).date(3),eq(i).date(4),eq(i).date(5),eq(i).date(6));
    end
    fprintf(fid,'%s\t%s\t%s\t%s\t%f\t%f\t%f\t%f\t%f\t%f\n',...
        eq(i).dstr,...
        sprintf(hms,eq(i).date(4:6)),...
        num2str(dayofyear(eq(i).date(1),eq(i).date(2),eq(i).date(3))),...
        seisfile,...
        eq(i).lat,...
        eq(i).long,...
        eq(i).depth,...
        eq(i).bazi,...
        eq(i).dis,...
        eq(i).Mw);
end
fclose(fid);
