function saverf_sac(i,para)

global config rf eq

if ispc
OUT_path = [config.RFdatapath '\' config.stnname];%path of PRFs
OUT_path1 = [config.cutdir '\' config.stnname];%path of cut out data
else
OUT_path = [config.RFdatapath '/' config.stnname];%path of PRFs
OUT_path1 = [config.cutdir '/' config.stnname];%path of cut out data
end


if( ~exist( OUT_path , 'dir') )
     mkdir( OUT_path ); end

switch para
    case 1
        seisrf = [rf(i).RadialRF_f1',rf(i).TransverseRF_f1'];        
        seiscut = [rf(i).R1,rf(i).T1,rf(i).Z1];
        f1 = rf(i).f4;
        f2 = rf(i).f2;
    case 2
        seisrf = [rf(i).RadialRF_f2',rf(i).TransverseRF_f2'];
        seiscut = [rf(i).R2,rf(i).T2,rf(i).Z2];
        f1 = rf(i).f3;
        f2 = rf(i).f2;
    case 3
        seisrf = [rf(i).RadialRF_f3',rf(i).TransverseRF_f3'];
        seiscut = [rf(i).R3,rf(i).T3,rf(i).Z3];
        f1 = rf(i).f1;
        f2 = rf(i).f2;
end
crfname = ['R','T'];
ccutname = ['R','T','Z'];
time = - config.extime_before  + rf(i).dt*(0:1:rf(i).RFlength-1);
Ev_para = taupTime('iasp91',rf(i).depth,rf(i).phase,'sta',[config.slat,config.slong],'evt',[rf(i).lat,rf(i).lon]);   
Ev_para = srad2skm(Ev_para(1).rayParam); 
for m=1:2
    tmp  = bsac(time,seisrf(:,m));
    tmp = ch(tmp,...
        'DELTA',  mean(diff(time)),...
        'O',      0,...
        'B',      time(1),...
        'E',      time(end),...
        'A',      rf(i).a,...
        'NPTS',   length(time),...
        'KSTNM',  config.stnname,...
        'KNETWK', config.netw,...
        'STLA',   config.slat,...
        'STLO',   config.slong,...
        'KCMPNM', crfname(m),...
        'EVLA',   rf(i).lat,...
        'EVLO',   rf(i).lon,...
        'EVDP',   rf(i).depth,...
        'MAG',    rf(i).Mw,...
        'BAZ',    rf(i).bazi,...
        'GCARC',  rf(i).dis,...
        'IZTYPE', 11,...      %'IO'; reference time is hypo time
        'NZYEAR', eq(i).date(1),...
        'NZJDAY', eq(i).date(7),...
        'NZHOUR', eq(i).date(4),...
        'NZMIN',  eq(i).date(5),...
        'NZSEC',  floor(eq(i).date(6)),...
        'a',     0,... 
        'Ka',    rf(i).phase,...
        'USER0',  Ev_para,...
        'KUSER0', 'Ray para',...
        'USER1',  config.f0,...
        'KUSER0', 'G fator',...
        'USER3',  f1,...
        'USER4',  f2,...
        'NZMSEC', round((eq(i).date(6) - floor(eq(i).date(6)))*1000));
    fname = [rf(i).seisfile '_' rf(i).phase '_' crfname(m) '.sac'];
    outname = fullfile(OUT_path,fname);
    wsac(outname, tmp);
 
end

if( ~exist( OUT_path1 , 'dir') )
        mkdir( OUT_path1 ); end
for m=1:3
    %access structure using dynamic filed names
    tmp  = bsac(time,seiscut(:,m));
    tmp = ch(tmp,...
        'DELTA',  mean(diff(time)),...
        'O',      0,...
        'B',      time(1),...
        'E',      time(end),...
        'A',      rf(i).a,...
        'NPTS',   length(time),...
        'KSTNM',  config.stnname,...
        'KNETWK', config.netw,...
        'STLA',   config.slat,...
        'STLO',   config.slong,...
        'KCMPNM', ccutname(m),...
        'EVLA',   rf(i).lat,...
        'EVLO',   rf(i).lon,...
        'EVDP',   rf(i).depth,...
        'MAG',    rf(i).Mw,...
        'BAZ',    rf(i).bazi,...
        'GCARC',  rf(i).dis,...
        'IZTYPE', 11,...      %'IO'; reference time is hypo time
        'NZYEAR', eq(i).date(1),...
        'NZJDAY', eq(i).date(7),...
        'NZHOUR', eq(i).date(4),...
        'NZMIN',  eq(i).date(5),...
        'NZSEC',  floor(eq(i).date(6)),...
        'a',     0,... 
        'Ka',    rf(i).phase,...
        'USER0',  Ev_para,...
        'KUSER0', 'Ray parameter',...
        'USER3',  f1,...
        'USER4',  f2,...
        'NZMSEC', round((eq(i).date(6) - floor(eq(i).date(6)))*1000));
    fname = [rf(i).seisfile '_RFdata_' ccutname(m) '.sac'];
    outname = fullfile(OUT_path1,fname);
    wsac(outname, tmp)
end
return
