function SL_checkrf

global config rf idx

rfch=figure('NumberTitle','off',...
        'name','Check PRFs after calculating',...
        'renderer','painters',...
        'ToolBar','none',...
        'Menubar','none',...
        'Tag','CheckRF',...
        'color','w',...
        'Position',[200 200 540 480],...
        'Pointer','crosshair', ...
        'PaperType',       config.PaperType,...
        'PaperOrientation','landscape',...
        'PaperUnits','centimeters');
    
load icon.mat;
backcol=[234   233   237]/255;
rfpanel(1)=uipanel('Units','pixel','Title','Receiver Function wave',...
    'FontSize',12,'Position',[10 10 520 470], 'BackgroundColor', backcol);

rfaxes=axes('Parent',rfpanel(1),'Units','pixel',...
            'Position',[40 90 460 320]);

idx = 1;

SL_RFviewer(idx);


uicontrol('Parent',rfpanel(1),'Units','pixel',...
    'Style','Pushbutton',...
    'Position',[40 20 50 40],...
    'cdata', icon.back,...
    'ToolTipString','back',...
    'Callback','idx=idx-1;if idx==0;idx=1;else;SL_RFviewer(idx);end');

uicontrol('Parent',rfpanel(1),'Units','pixel',...
    'Style','Pushbutton',...
    'Position',[110 20 50 40],...
    'cdata', icon.next,...
    'ToolTipString','next',...
    'Callback','idx=idx+1;if idx>length(rf);idx =1;button = MFquestdlg([ 0.4 , 0.42 ],''Do you want to quit the database?'',''PS_RecFunc'',''Yes'',''No'',''Yes'');if strcmp(button, ''Yes'');close(gcf);else;SL_RFviewer(idx);end;else;SL_RFviewer(idx);end');

uicontrol('Parent',rfpanel(1),'Units','pixel',...
    'Style','Pushbutton',...
    'Position',[180 20 50 40],...
    'cdata', icon.camera,...
    'ToolTipString','print wave',...
    'Callback','printdlg(gcbf)');

uicontrol('Parent',rfpanel(1),'Units','pixel',...
    'Style','Pushbutton',...
    'Position',[250 20 50 40],...
    'cdata', icon.save,...
    'ToolTipString','save PRF data',...
    'Callback','saverf(idx)');

uicontrol('Parent',rfpanel(1),'Units','pixel',...
    'Style','edit',...
    'BackgroundColor','w',...
    'Position',[320 25 80 30],...
    'ToolTipString','Image output directory',...
    'String', idx,...
    'Callback','idx=str2num(get(gcbo,''String''));')

uicontrol('Parent',rfpanel(1),'Units','pixel',...
    'Style','Pushbutton',...
    'Position',[430 20 70 40],...
    'String', 'plot wave',...
    'ToolTipString',['plot ' num2str(idx) 'th PRF'],...
    'Callback','SL_RFviewer(idx)');


set(rfch,'KeyPressFcn',{@rfKeyPress,rfch});